TOPIC_NAME = 'bus_data_mqtt'
INFLUX_TOKEN = 'zqY4VrrlXp7RhZAELoPeW4FyKqm0jPR61nQ2Q9YVEyW21TBTVwuxZktMjaLARyePk1vAdiEyNo7Qd-g_rVOLMA=='
INFLUX_URL = 'http://localhost:8086'
INFLUX_ORG = 'bus_group'
INFLUX_BUCKET = 'bus_tracker'
INFLUX_URL_RECV = 'http://localhost:8086'